image: brianegan/dart-lcov:v2

stages:
  - test

unit_test:
  stage: test
  script: pub get && pub run test

coverage:
  stage: test
  script: export PATH="$PATH":"~/.pub-cache/bin" && pub get && pub global activate dart_dev && dart_dev coverage --no-open
