language: dart
sudo: false
dart:
  - dev
  - stable
with_content_shell: false
script:
  - dartfmt -n ./lib --set-exit-if-changed
  - dartanalyzer --fatal-infos --fatal-warnings ./
  - pub run test test/epic_middleware_test.dart


