name: redux_epics
author: Brian Egan <brian@brianegan.com>
description: A redux.dart Middleware that helps you perform side effects using Streams
homepage: https://github.com/brianegan/dart_redux_epics
version: 0.13.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  rxdart: ">=0.23.0 <0.24.0"
  redux: ">=4.0.0 <5.0.0"

dev_dependencies:
  test: ">=0.12.33 <1.5.1"
  pedantic: ">=1.9.0 <2.0.0"
