name: redux_epics
author: Brian Egan <brian@brianegan.com>
description: A redux.dart Middleware to support the use of Streams
homepage: https://github.com/brianegan/dart_redux_epics
version: 0.4.0

dependencies:
  rxdart: ">=0.4.0 <0.5.0"
  redux: ">=1.1.0 <2.0.0"

dev_dependencies:
  test: 0.12.15+9
  coverage: any
