name: redux_epics
description: A redux.dart Middleware that helps you perform side effects using Streams
homepage: https://github.com/brianegan/dart_redux_epics
version: 0.15.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  rxdart: ^0.28.0
  redux: ">=5.0.0 <6.0.0"

dev_dependencies:
  test: ^1.25.8
  pedantic: ">=1.11.0 <2.0.0"
